add globality build.json
globality-corp/cookiecutter-microcosm-service pull request #29
Opened 2019-06-07 21:58 UTC by stephensxuglobality

https://globality.atlassian.net/browse/DEVOPS-80

Goal: Add .globality/build.json file so that cookiecutted projects will be able to use `globality-build`

2019-06-07 22:00 UTC, KensoDev requested changes

2019-06-07 22:00 UTC, KensoDev commented on cookiecutter.json
> +    "database": "postgres, elasticsearch, memcached, neo4j"
There could also be no dB

2019-06-07 22:17 UTC, stephensxuglobality commented
@KensoDev how about removing db section

2019-06-10 20:13 UTC, KensoDev approved these changes

2019-06-10 20:13 UTC, merged